site_name: mcp-declarative-java-sdk documentation
site_url: https://codeboyzhou.github.io/mcp-declarative-java-sdk
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
    - announce.dismiss
    - search.suggest
    - content.tabs.link

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/codeboyzhou/mcp-declarative-java-sdk
repo_name: mcp-declarative-java-sdk

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

copyright: © 2025 <a href="https://github.com/codeboyzhou">codeboyzhou</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codeboyzhou

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
