name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: maven build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build with JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          cache: maven
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
